version: "3.9"

services:
  caddy:
    image: caddy:2.8-alpine
    container_name: caddy_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP (Let's Encrypt, редиректы)
      - "443:443"    # HTTPS (Let's Encrypt, SSL)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true  # сеть должна быть создана заранее: docker network create caddy_net.

volumes:
  caddy_data:
  caddy_config: